openapi: "3.0.0"
info:
  version: 1.0.0
  title: DeviantArt Eclipse
  description: Unofficial documentation for the internal DeviantArt Eclipse API
  license:
    name: MIT
  contact:
    name: Kathryn DiPippo (for spec updates, not API feature updates)
    url: https://kathryndipippo.com
    email: dipippo.k@gmail.com
servers:
  - url: https://www.deviantart.com/_napi/shared_api
tags:
- name: Deviations
paths:
  /deviation/extended_fetch:
    $ref: "./resources/deviation/extended_fetch.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"