openapi: "3.0.0"
info:
  version: 1.0.0
  title: DeviantArt Eclipse
  description: Unofficial documentation for the internal DeviantArt Eclipse API
  license:
    name: MIT
  contact:
    name: Kathryn DiPippo (for spec updates, not API feature updates)
    url: https://kathryndipippo.com
    email: dipippo.k@gmail.com
servers:
  - url: https://www.deviantart.com/_napi/shared_api
tags:
- name: Deviations
paths:
  /deviation/extended_fetch:
    $ref: "./resources/deviation/extended_fetch.yaml"
  /deviation/delete:
    $ref: "./resources/deviation/delete.yaml"
  /journal/create:
    $ref: "./resources/journal/create.yaml"
  /journal/update/content:
    $ref: "./resources/journal/update/content.yaml"
  /journal/publish:
    $ref: "./resources/journal/publish.yaml"
  /deviation/groups:
    $ref: "./resources/deviation/groups.yaml"
  /deviation/group_folders:
    $ref: "./resources/deviation/group_folders.yaml"
  /deviation/group_add:
    $ref: "./resources/deviation/group_add.yaml"
  /status/create:
    $ref: "./resources/status/create.yaml"
  /status/publish:
    $ref: "./resources/status/publish.yaml"
  /status/delete:
    $ref: "./resources/status/delete.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
