name: Lint OpenAPI Spec with Spectral

on:
  pull_request:
    paths:
    - 'spec/**'

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stoplightio/spectral-action@v0.7.3
      with:
        file_glob: 'openapi.yaml'
