name: Lint OpenAPI Spec with Spectral

on: [push]

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.6.1
        with:
          file_glob: 'openapi.yaml'
