name: Lint Python with Wemake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
